@host=https://localhost:7098
POST {{host}}/auth/register
Content-Type: application/json

{
    "FirstName": "John",
    "LastName": "Doe",
    "Email":"dilshodbekkhamidov@gmail.com",
    "Password": "123456"
}
